"""Constants list."""
from toga.style.pack import MONOSPACE

NO_VALUE = "----------"
POLYNOMIAL = "polynomial"

LOGO_SIZE = 192
WINDOW_SIZE = (1200, 650)

SMALL_PADDING = 2
BIG_PADDING = 5
RECORD_WINDOW_SIZE = (1000, 500)
COLUMN_WIDTH = 150

PARAMETER_WIDTH = 75
LABEL_WIDTH = 150
SELECTION_WIDTH = 200
SMALL_INPUT_WIDTH = 100
LONG_INPUT_WIDTH = 350
LINE_HEIGHT = 30

FOOTER_FONT_FAMILY = MONOSPACE
SMALL_FONT_SIZE = 10
