NO_VALUE = "----------"
COSTUMED = "costumed"

X_COLUMN = "x_column"
XERR_COLUMN = "xerr_column"
Y_COLUMN = "ycolumn"
YERR_COLUMN = "yerr_column"

SMALL_PADDING = 2
BIG_PADDING = 5
SIZE = (700, 400)
PARAMETER_WIDTH = 75
SELECTION_WIDTH = 200
INPUT_WIDTH = 200
LINE_HEIGHT = 30
